spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mockdata
    username: root
    password: ENC(A15/tzjhWRbV/b4CZE2Ae4Csfejwxnai7gyC1i8hCN37Qek0Bn2VC6uEr5iUv0aN)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
  profiles:
    include: secret
cloud:
  aws:
    credentials:
      accessKey: ENC(z9aqywsK0B3XPlAheiT+C/PVT56tcZrgI/I0V6pOUKeLU90m/THWdD3cQnpLkDvGougjwqVgpW8u4+ZAi04lVQ==)
      secretKey: ENC(04eF+Z7ygPEiu06gV3jYS7zh21ZJiS0ecdQa7JvQji2yw6D1TKO/rJCxR+TPVb/S+0z0LrqNRqOjaV6rEs1ClUVrdpMUcTNu4Gg1sh0y864=)
    s3:
      bucket: ENC(fnnh/uhVNcgQ4R8aqAkbmYJKJkx/I6B1BnsDoc34bIHYcDIauJNgDgyOqGLfQtkXzVURIkUODNwMkkELziq4sA==)
    region:
      static: ap-northeast-2
    stack:
      auto: false